#!/usr/bin/env python3
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument('input')
parser.add_argument('output')
args = parser.parse_args()

with open(args.input, 'r') as f:
    input_data = f.read()
with open(args.output, 'r') as f:
    output_data = f.read()

if input_data != output_data:
    print('Answers differ')
    sys.exit(1)
